[package]
name = "simpletaskmgr"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
gtk4 = { version = "0.11", features = ["v4_10"] }
log = "0.4.33"
procfs = "0.18.0"
simplelog = "0.12.2"
users = "0.11.0"
anyhow = "1.0.104"
thiserror = "2.0.20"
libc = "0.2.189"
cairo-rs = "0.22"
glib = "0.22"

[lib]
name = "simpletaskmgr"
path = "src/lib.rs"

[[bin]]
name = "simpletaskmgr"
path = "src/main.rs"

[dev-dependencies]
rstest = "0.26.1"
